#!/usr/bin/env bash

git config --global user.email "noreply@travis.com"
git config --global user.name "Travis CI"

git config credential.helper "store --file=.git/credentials"
echo "https://${GH_TOKEN}:@github.com" > .git/credentials

mkdir -p opt/apk
cp -R app/build/outputs/apk/app-debug.apk opt/apk/latest.apk

git add -A
git commit --signoff -F- <<EOF
Travis CI: Updated apk from latest build
Apk: opt/apk/latest.apk
Last commit: $(git log -1 --pretty=%B)
Date: $(date)
[ci skip]
EOF

git branch apk-update
git checkout master
git merge apk-update
git push origin master
