#!/usr/bin/env bash

cat << "EOF"

 ('-. .-.               _ (`-.    ('-.  _  .-')
( OO )  /              ( (OO  ) _(  OO)( \( -O )
,--. ,--.  ,--.   ,--._.`     \(,------.,------.
|  | |  |   \  `.'  /(__...--'' |  .---'|   /`. '
|   .|  | .-')     /  |  /  | | |  |    |  /  | |
|       |(OO  \   /   |  |_.' |(|  '--. |  |_.' |
|  .-.  | |   /  /\_  |  .___.' |  .--' |  .  '.'
|  | |  | `-./  /.__) |  |      |  `---.|  |\  \
`--' `--'   `--'      `--'      `------'`--' '--'

EOF

COMMIT_MSG="$(git log -1)"

if [[ $COMMIT_MSG != *"[apk skip]"* ]]
then
git config --global user.email "travis@travis-ci.org"
git config --global user.name "Travis CI"

git config credential.helper "store --file=.git/credentials"
echo "https://${GH_TOKEN}:@github.com" > .git/credentials

cp -R app/build/outputs/apk/debug/app-debug.apk apk/canary.apk

git add apk/canary.apk
git commit -F- <<EOF
Build #${TRAVIS_BUILD_NUMBER}: Canary APK updated from CI
$COMMIT_MSG

[ci skip]
EOF

git branch apk-update
git checkout master
git merge apk-update
git push origin master
else
echo "[apk skip] found in commit message. Skipping APK upload."
fi
